### ISSUE TITLE
The URIs should be meaningful at least 

### ISSUE THREAD

**Issue by salman-** [JaanJanno/ConsultationWeb#79]
I told you to use resource model to generate the URIs, but it seems that you didn't.
So at least try to make them meaningful.
For instance you choose /requests/{id} for accepting requests, and then it redirects to the /requests/ACCEPTED

1- You do not use upper case letter in URIs. How manytimes have you seen in the websites that people use upper case for uri?????

2- You did not clarify what do you want to do with this request.
A possible correct option would be /requests/{id}/accept  @TKasekamp

**Comment by TKasekamp** [comment]
It redirects to Accepted requests as that is how I believe the functionality should work. The consultant sets the consultation as accepted and is then redirected to the accepted requests page where he can work with it further.
1. The URI is uppercase because the enum value for status is ACCEPTED (in uppercase). The controller receives the status as an enum and then displays it. If we want to do it with downcase, then the controller has to set it to uppercase and then to enum. I talked about it with @JaanJanno and he was okay with this solution. But if neccessary, I'll make the controller have the status in downcase.
2. The '/requests/{id}' POST to set as accepted is @JaanJanno 's idea. That's how the REST API was first designed. As we won't have any status change as a direct button action (no button for SCHEDULED or CLOSED), editing the URI isn't strictly neccessay.

**Comment by JaanJanno** [comment]
I agree we could improve the URLs. I reassigned the issue to myself at the moment.
